@{
  "Common.MenuQuit"             = "[ 終了 ]"
  "Common.MenuCancel"           = "[ キャンセル ]"
  "Common.PressAnyKey"          = "任意のキーでメニューに戻ります..."
  "Common.FileNotFound"         = "{0} が見つかりません: {1}"
  "Common.Error"                = "エラー: {0}"
  "Common.Cancelled"            = "キャンセルしました。"
  "Common.Required"             = "必須項目を入力してください。"

  "Toolkit.Banner.Title"        = "ネットワークツールキット"
  "Toolkit.Banner.Version"      = "Ver {0}"
  "Toolkit.Menu.Title"          = "機能を選択してください (↑↓ / Enter / ESC)"
  "Toolkit.StartingTool"        = "起動中: {0}"
  "Toolkit.Exit.Thanks"         = "ご利用ありがとうございました。"
  "Toolkit.Exit.VersionLine"    = "バージョン: {0}"
  "Toolkit.Exit.UpdatedLine"    = "最終更新: {0}"
  "Toolkit.AdminRequired"       = "このツールは管理者権限で起動してください。"

  "Nat.List.Title"              = "ポートマッピング一覧"
  "Nat.List.Empty"              = "ポートマッピングはありません。"
  "Nat.List.Count"              = "件数: {0}"
  "Nat.Menu.Title"              = "NAT ツール (↑↓ / Enter / ESC)"
  "Nat.Menu.Help"               = "一覧・作成・削除を選択してください。"

  "Nat.Table.ListenAddress"     = "宿主IP"
  "Nat.Table.ListenPort"        = "宿主ポート"
  "Nat.Table.ConnectAddress"    = "転送先IP"
  "Nat.Table.ConnectPort"       = "転送先ポート"
  "Nat.Table.Protocol"          = "タイプ"

  "Nat.Prompt.ListenAddress"    = "宿主IP (Enter=0.0.0.0)"
  "Nat.Prompt.ListenPort"       = "宿主ポート"
  "Nat.Prompt.ConnectAddress"   = "転送先IP"
  "Nat.Prompt.ConnectPort"      = "転送先ポート"

  "Nat.New.Success"             = "ポートマッピングを作成しました。"
  "Nat.New.FwAlreadyOpen"       = "防火壁は既に開放済みです。Port={0}, RuleCount={1}"
  "Nat.New.FwAutoOpened"        = "防火壁を自動開放しました。Port={0}, Rule={1}"
  "Nat.New.FwAlreadyOpenByName" = "防火壁ルールは既に存在します。Port={0}, Rule={1}"
  "Nat.New.FwAutoOpenFailed"    = "防火壁の自動開放に失敗しました。Port={0}, Error={1}"
  "Nat.Remove.SelectTitle"      = "削除対象を選択してください"
  "Nat.Remove.SelectHint"       = "↑↓で選択 / Enter 決定 / ESC 戻る"
  "Nat.Remove.Confirm"          = "削除しますか? {0}:{1} (yes で確定)"
  "Nat.Remove.Success"          = "削除完了: {0}:{1}"

  "Nat.Error.AdminRequired"     = "管理者権限で実行してください。"
  "Nat.Error.Netsh"             = "netsh 実行エラー: {0}"
  "Nat.Error.OperationFailed"   = "処理に失敗しました: {0}"
  "Nat.Error.AlreadyExists"     = "既に存在します: {0}:{1}"

  "Fw.Menu.Title"               = "Firewall ツール (↑↓ / Enter / ESC)"
  "Fw.Menu.Help"                = "確認・開放・削除を選択してください。"
  "Fw.Prompt.Port"              = "ポート番号"
  "Fw.Error.InvalidPort"        = "ポート番号が不正です。"
  "Fw.Error.OperationFailed"    = "処理に失敗しました: {0}"
  "Fw.Check.Closed"             = "ポート {0} を開放する受信許可ルールは見つかりません。"
  "Fw.Check.Opened"             = "ポート {0} は開放済みです。該当ルール数: {1}"
  "Fw.New.Success"              = "ルール作成完了: {0} (Port={1}, Protocol={2})"
  "Fw.New.AlreadyExists"        = "既存ルールを利用します: {0}"
  "Fw.Remove.NotFound"          = "ポート {0} に該当する開放ルールはありません。"
  "Fw.Remove.Found"             = "ポート {0} の開放ルールを検出: {1}"
  "Fw.Remove.Confirm"           = "ポート {0} の開放ルールを削除しますか? (yes で確定)"
  "Fw.Remove.Success"           = "ポート {0} のルールを削除しました。削除件数: {1}"
  "Fw.Table.DisplayName"        = "ルール名"
  "Fw.Table.Protocol"           = "プロトコル"
  "Fw.Table.LocalPort"          = "ローカルポート"
  "Fw.Table.Profile"            = "プロファイル"
}
