@{
  "Common.MenuQuit"             = "[ Exit ]"
  "Common.MenuCancel"           = "[ Cancel ]"
  "Common.PressAnyKey"          = "Press any key to return to menu..."
  "Common.FileNotFound"         = "{0} not found: {1}"
  "Common.Error"                = "Error: {0}"
  "Common.Cancelled"            = "Cancelled."
  "Common.Required"             = "Required value is missing."

  "Toolkit.Banner.Title"        = "Network Toolkit"
  "Toolkit.Banner.Version"      = "Ver {0}"
  "Toolkit.Menu.Title"          = "Select function (↑↓ / Enter / ESC)"
  "Toolkit.StartingTool"        = "Starting: {0}"
  "Toolkit.Exit.Thanks"         = "Thanks for using this toolkit."
  "Toolkit.Exit.VersionLine"    = "Version: {0}"
  "Toolkit.Exit.UpdatedLine"    = "Last updated: {0}"
  "Toolkit.AdminRequired"       = "Please start this toolkit as Administrator."

  "Nat.List.Title"              = "Port Mappings"
  "Nat.List.Empty"              = "No port mappings found."
  "Nat.List.Count"              = "Count: {0}"
  "Nat.Menu.Title"              = "NAT Tool (↑↓ / Enter / ESC)"
  "Nat.Menu.Help"               = "Choose list, create, or delete."

  "Nat.Table.ListenAddress"     = "Host IP"
  "Nat.Table.ListenPort"        = "Host Port"
  "Nat.Table.ConnectAddress"    = "Target IP"
  "Nat.Table.ConnectPort"       = "Target Port"
  "Nat.Table.Protocol"          = "Type"

  "Nat.Prompt.ListenAddress"    = "Host IP (Enter=0.0.0.0)"
  "Nat.Prompt.ListenPort"       = "Host Port"
  "Nat.Prompt.ConnectAddress"   = "Target IP"
  "Nat.Prompt.ConnectPort"      = "Target Port"

  "Nat.New.Success"             = "Port mapping created."
  "Nat.New.FwAlreadyOpen"       = "Firewall is already open. Port={0}, RuleCount={1}"
  "Nat.New.FwAutoOpened"        = "Firewall port opened automatically. Port={0}, Rule={1}"
  "Nat.New.FwAlreadyOpenByName" = "Firewall rule already exists. Port={0}, Rule={1}"
  "Nat.New.FwAutoOpenFailed"    = "Failed to auto-open firewall port. Port={0}, Error={1}"
  "Nat.Remove.SelectTitle"      = "Select mapping to delete"
  "Nat.Remove.SelectHint"       = "Use ↑↓ / Enter / ESC"
  "Nat.Remove.Confirm"          = "Delete {0}:{1}? (type yes to confirm)"
  "Nat.Remove.Success"          = "Deleted: {0}:{1}"

  "Nat.Error.AdminRequired"     = "Run as Administrator."
  "Nat.Error.Netsh"             = "netsh execution failed: {0}"
  "Nat.Error.OperationFailed"   = "Operation failed: {0}"
  "Nat.Error.AlreadyExists"     = "Mapping already exists: {0}:{1}"

  "Fw.Menu.Title"               = "Firewall Tool (↑↓ / Enter / ESC)"
  "Fw.Menu.Help"                = "Choose check, open, or delete."
  "Fw.Prompt.Port"              = "Port number"
  "Fw.Error.InvalidPort"        = "Invalid port number."
  "Fw.Error.OperationFailed"    = "Operation failed: {0}"
  "Fw.Check.Closed"             = "No inbound allow rule found for port {0}."
  "Fw.Check.Opened"             = "Port {0} is open. Matched rules: {1}"
  "Fw.New.Success"              = "Rule created: {0} (Port={1}, Protocol={2})"
  "Fw.New.AlreadyExists"        = "Rule already exists: {0}"
  "Fw.Remove.NotFound"          = "No open rules found for port {0}."
  "Fw.Remove.Found"             = "Open rules found for port {0}: {1}"
  "Fw.Remove.Confirm"           = "Delete open rules for port {0}? (type yes)"
  "Fw.Remove.Success"           = "Port {0} rules deleted. Removed count: {1}"
  "Fw.Table.DisplayName"        = "Rule Name"
  "Fw.Table.Protocol"           = "Protocol"
  "Fw.Table.LocalPort"          = "Local Port"
  "Fw.Table.Profile"            = "Profile"
}
